### ISSUE TITLE
in eval.py, IndexError: list index out of range

### ISSUE THREAD

**Issue by junwoopark92** [machine-learning-challenge/mlc2017-online#1]
In cats_on_dogs baseline code, An error occurs during the execution of the command below

python eval.py --eval_data_pattern='/path/to/validation/files' --train_dir=/tmp/cvd_train --model=LogisticModel --run_once=True

error log>
image_id_batch = tf.get_collection("image_id_batch")[0]
IndexError: list index out of range

in my case, modifying this line to tf.get_collection("id_batch")[0] solves error

is this error ?

**Comment by mikigom** [comment]
I solve this issue by replacing `tf.add_to_collection("id_batch", image_id_batch)` of 146 line to 
  ```tf.add_to_collection("image_id_batch", image_id_batch)```. It looks just a typo.
